### ISSUE TITLE
ArchLinux Device

### ISSUE THREAD

**Issue by uaquax** [omnitix/scu#2]
Wrong device

OS: Arch Linux x86_64

`cargo run --release`

Expected behavior:
> Device: 81Q5 Legion Y7000P 2019

Actual behavior:
> Devicel LENOVO LNVNB161216

**Comment by Sk44rt** [comment]
send content of those files (if they are exists):
/sys/devices/virtual/dmi/id/board_vendor
/sys/devices/virtual/dmi/id/board_name
/sys/devices/virtual/dmi/id/product_name
/sys/devices/virtual/dmi/id/product_version
/sys/firmware/devicetree/base/model

**Comment by Sk44rt** [comment]
and what does mean expected? where you took this device name?

**Comment by uaquax** [comment]
> and what does mean expected? where you took this device name?

очікувана поведінка

**Comment by uaquax** [comment]
> send content of those files (if they are exists): /sys/devices/virtual/dmi/id/board_vendor /sys/devices/virtual/dmi/id/board_name /sys/devices/virtual/dmi/id/product_name /sys/devices/virtual/dmi/id/product_version /sys/firmware/devicetree/base/model

|   /sys/devices/virtual/dmi/id/board_vendor    |   LENOVO  |
|   /sys/devices/virtual/dmi/id/board_name  |   LNVNB161216 |
|   /sys/devices/virtual/dmi/id/product_name    |   81Q5    |
|   /sys/devices/virtual/dmi/id/product_version |   Legion Y7000P 2019  |
|   /sys/firmware/devicetree/base/model |   No such file or directory   |

**Comment by uaquax** [comment]
> where you took this device name?

neofetch

**Comment by uaquax** [comment]
> and what does mean expected? 
expected behavior = очікувана поведінка

**Comment by Sk44rt** [comment]
Solved in new commit
